### ISSUE TITLE
您好，我下载了整个文件夹，也在百度云里下载了词向量文件，运行main.py的时候出现了错误，希望能得到您的解答，谢谢！

### ISSUE THREAD

**Issue by lxh0723** [DefuLi/Emotional-Analysis-of-Internet-News#2]
Traceback (most recent call last):
  File "D:/Python/梁花/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/main.py", line 175, in <module>
    IDX, TEXT, _, _, _ = getVocab()
  File "D:/Python/梁花/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/main.py", line 62, in getVocab
    fields=[('id', IDX), ('text', TEXT), ('label', LABEL)])
  File "C:\Users\花花\AppData\Roaming\Python\Python37\site-packages\torchtext\data\dataset.py", line 78, in splits
    os.path.join(path, train), **kwargs)
  File "C:\Users\花花\AppData\Roaming\Python\Python37\site-packages\torchtext\data\dataset.py", line 269, in __init__
    next(reader)
  File "C:\Users\花花\AppData\Roaming\Python\Python37\site-packages\torchtext\utils.py", line 130, in unicode_csv_reader
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long

**Comment by lxh0723** [comment]
而且from net import net也标出红线了，说是无法“解析的引用”

**Comment by DefuLi** [comment]
第一个问题：你下载的词向量放入指定的文件夹里，并且要在main.py文件中改成正确的路径。下载的词向量后缀名是txt，如果你下载的后缀名不是txt，直接重命名，把后缀名改成txt。

第二个问题：net是我写的一个类，你看下你下载整个文件夹的时候，有没有net.py，如果有的话，请在pycharm里右击项目名，make directory as---sources root

**Comment by lxh0723** [comment]
train, val, test = data.TabularDataset.splits(path='D:/Python/梁花/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/torchtextfiles', train='train.csv', validation='val.csv',
                                                  test='test.csv', format='csv', skip_header=True,
                                                  fields=[('id', IDX), ('text', TEXT), ('label', LABEL)])

    vects = torchtext.vocab.Vectors(name='D:/Python/梁花/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/wordfiles/Sgns.context.word-word.dynwin5.thr10.neg5.dim300.iter5.txt',
                                    cache='cachefiles/')

把文件路径修改了，但是还是会报错
Traceback (most recent call last):
  File "D:/Python/梁花/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/main.py", line 175, in <module>
    IDX, TEXT, _, _, _ = getVocab()
  File "D:/Python/梁花/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/main.py", line 62, in getVocab
    fields=[('id', IDX), ('text', TEXT), ('label', LABEL)])
  File "C:\Users\花花\AppData\Roaming\Python\Python37\site-packages\torchtext\data\dataset.py", line 78, in splits
    os.path.join(path, train), **kwargs)
  File "C:\Users\花花\AppData\Roaming\Python\Python37\site-packages\torchtext\data\dataset.py", line 269, in __init__
    next(reader)
  File "C:\Users\花花\AppData\Roaming\Python\Python37\site-packages\torchtext\utils.py", line 130, in unicode_csv_reader
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long

**Comment by lxh0723** [comment]
因为cuda版本的原因，我重新装了torch，以上的问题解决了。只是现在又出现了另一个问题
Traceback (most recent call last):
  File "D:/Python/梁花/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/main.py", line 178, in <module>
    net = Net(len(TEXT.vocab), 300, HIDDEN_DIM).to(device)  # embedding_dim=300, hidden_dim=128
  File "C:\Users\花花\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 381, in to
    return self._apply(convert)
  File "C:\Users\花花\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\Users\花花\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "C:\Users\花花\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "C:\Users\花花\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\cuda\__init__.py", line 163, in _lazy_init
    _cudart = _load_cudart()
  File "C:\Users\花花\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\cuda\__init__.py", line 60, in _load_cudart
    lib = find_cuda_windows_lib()
  File "C:\Users\花花\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\cuda\__init__.py", line 33, in find_cuda_windows_lib
    out = out.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 9: invalid start byte

**Comment by lxh0723** [comment]
我还把utils.py里的csv.field_size_limit(sys.maxsize)注释了，如果不注释还是会有溢出问题

**Comment by lxh0723** [comment]
请问您用GPU加速跑了多久才出的结果呢？

**Comment by DefuLi** [comment]
我在你的信息里没有看出错误具体由什么造成的。
GPU加速一般跑半个小时就行了，这只是个LSTM，不费时的。

**Comment by lxh0723** [comment]
好的，十分感谢
