### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ray184550061** [DefuLi/Emotional-Analysis-of-Internet-News#4]
C:\Users\hp-pc\AppData\Local\Programs\Python\Python37\python.exe G:/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/main.py

  0%|          | 0/239733 [00:00<?, ?it/s]Skipping token b'636000' with 1-dimensional vector [b'300']; likely a header
  0%|          | 0/239733 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "G:/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/main.py", line 175, in <module>
    IDX, TEXT, _, _, _ = getVocab()
  File "G:/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/main.py", line 65, in getVocab
    cache='cachefiles/')
  File "C:\Users\hp-pc\AppData\Roaming\Python\Python37\site-packages\torchtext\vocab.py", line 323, in __init__
    self.cache(name, cache, url=url, max_vectors=max_vectors)
  File "C:\Users\hp-pc\AppData\Roaming\Python\Python37\site-packages\torchtext\vocab.py", line 406, in cache
    dim))

RuntimeError: Vector for token b'",' has 301 dimensions, but previously read vectors have 299 dimensions. All vectors must have the same number of dimensions.
![QQ图片20200108121622](https://user-images.githubusercontent.com/57591445/71950015-b671d380-3210-11ea-9658-f03f052c435d.png)

请问这个应该怎么处理呢

**Comment by ray184550061** [comment]
代码没有动过，不知道出现了什么问题。想请教一下应该怎么处理呢？谢谢！

**Comment by ray184550061** [comment]
还有一个问题就是在运行预处理文件时，这个问题应该怎么解决呢，谢谢！

C:\Users\hp-pc\AppData\Local\Programs\Python\Python37\python.exe G:/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/preprocess.py
train数据集个数:7340
label数据集个数:7355
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\hp-pc\AppData\Local\Temp\jieba.cache
Loading model cost 1.092 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "G:/Emotional-Analysis-of-Internet-News-master/CCF_NewsSenAna/preprocess.py", line 258, in <module>
    train_clear = train_clear('testfiles/Test_Addlabel.csv')
TypeError: 'list' object is not callable
![QQ图片20200108170824](https://user-images.githubusercontent.com/57591445/71964898-930f4e80-3239-11ea-803e-6b45985a1835.png)

**Comment by DefuLi** [comment]
train_clear = train_clear('testfiles/Test_Addlabel.csv')
你把等号左边的变量名改成别的试试
